# SPDX-License-Identifier: MPL-2.0
# This workflow is managed by gh actions-lock.

name: CI
on:
  push:
    branches: [main]
  pull_request:
permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: leanprover/lean-action@v1.5.0
      - name: No sorries
        run: "! grep -rn 'sorry' Marches/ Marches.lean"
